CFLAGS = -c -DPC -DMSC -AL -I..\..\src
LIB = ..\..\src\vogle.lib

.c.obj:
	cl $(CFLAGS) $*.c

h2v.obj: h2v.c h2v.h

getchar.obj: getchar.c

hdisp.obj: hdisp.c

fdisp.obj: fdisp.c

h2v.exe: h2v.obj getchar.obj
	link h2v+getchar,,nul;

hdisp.exe: hdisp.obj getchar.obj $(LIB)
	link hdisp+getchar,,nul,$(LIB)

fdisp.exe: fdisp.obj $(LIB)
	link fdisp+getchar,,nul,$(LIB)

